version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB_NAME: ${DB_NAME}
    container_name: EcommerceFullStack
    volumes:
      - ./postgres:/var/lib/postgresql/data
    command: -p 5433